deploy infra

diff --git a/.github/workflows/apply-terraform.yml b/.github/workflows/apply-terraform.yml
--- a/.github/workflows/apply-terraform.yml
+++ b/.github/workflows/apply-terraform.yml
@@ -41,6 +41,10 @@ jobs:
         run: |
           terraform workspace select $WORKSPACE || terraform workspace new $WORKSPACE
 
+      - name: Remove existing IAM Role from Terraform state if present
+        run: |
+          terraform state rm module.lb_role.aws_iam_role.this[0] || echo "Role not found in state"
+          
       - name: Import Existing IAM Role if Present
         id: import_role
         run: |
